### ISSUE TITLE
ClassNotFoundException: com.google.android.play.core.assetpacks.AssetPackManagerFactory

### ISSUE THREAD

**Issue by CarlosCabarcos** [googlecodelabs/unity-gamepad#4]
Hi there,

While following the tutorial: https://developer.android.com/codelabs/unity-gamepad#4, on Step 5: "Testing asset packs locally", the App builds and installs on the device without any issues, but as soon as it starts running the "LoadingScene", I'm getting the following error:

```
08-22 17:01:21.819: E/Unity(11720): AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.play.core.assetpacks.AssetPackManagerFactory
08-22 17:01:21.819: E/Unity(11720): java.lang.ClassNotFoundException: com.google.android.play.core.assetpacks.AssetPackManagerFactory
08-22 17:01:21.819: E/Unity(11720): 	at java.lang.Class.classForName(Native Method)
08-22 17:01:21.819: E/Unity(11720): 	at java.lang.Class.forName(Class.java:454)
08-22 17:01:21.819: E/Unity(11720): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-22 17:01:21.819: E/Unity(11720): 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
08-22 17:01:21.819: E/Unity(11720): 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
08-22 17:01:21.819: E/Unity(11720): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-22 17:01:21.819: E/Unity(11720): 	at android.os.Looper.loopOnce(Looper.java:210)
08-22 17:01:21.819: E/Unity(11720): 	at android.os.Looper.loop(Looper.java:299)
08-22 17:01:21.819: E/Unity(11720): 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
08-22 17:01:21.819: E/Unity(11720): Caused by: java.lang.ClassNotFoundException: com.google.android.play.core.assetpacks.AssetPackManagerFactory
08-22 17:01:21.819: E/Unity(11720): 	... 9 more
08-22 17:01:21.819: E/Unity(11720):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
08-22 17:01:21.819: E/Unity(11720):   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <000000
```

I've been Googling trying to find a solution and I only found one person with the same issue and a solution:

https://github.com/google/play-unity-plugins/issues/180

However, the solution proposed is not working for me.

Does anyone have any idea of what might be causing this or how to solve it?

Thank you.

PS: I'm using Unity 2019.4.13f1, which is supposed to be one of the recommended versions to follow the tutorial.

**Comment by CarlosCabarcos** [comment]
After trying 20 millions things, I finally got it to work. The solution for me, was to do the following:

1. Go to Player Settings -> Publishing settings section and tick "Custom Main Gradle Template".
2. Open the Custom Gradle file (mainTemplate.gradle) that should appear in the Assets/Plugins/Android folder.
3. Edit the dependencies section and add the line:     implementation 'com.google.android.play:asset-delivery:2.0.0'

Hope it helps save anyone who faces the same problem a few hours of troubleshooting.

PS: I also updated the project to Unity 2021.3.1f1, but I don't think this matters much. It's just one more of the millions things I tried.
